-- =============================================================================
-- ArcadiaDimension — Visual Warehouse Designer
-- Database schema for PostgreSQL 15+ (Neon compatible)
--
-- Run this file once on an empty database (Neon SQL Editor or psql).
-- It is idempotent: re-running it will not drop or duplicate anything.
-- Demo data lives in database/demo.sql and must be executed afterwards.
-- =============================================================================

create extension if not exists pgcrypto;  -- gen_random_uuid()
create extension if not exists pg_trgm;   -- fast ILIKE search on article codes

-- -----------------------------------------------------------------------------
-- Shared trigger: keeps updated_at current on every UPDATE
-- -----------------------------------------------------------------------------
create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- -----------------------------------------------------------------------------
-- users: accounts that own warehouses
-- -----------------------------------------------------------------------------
create table if not exists users (
  id            uuid primary key default gen_random_uuid(),
  email         varchar(254) not null,
  name          varchar(80)  not null,
  password_hash text         not null,
  created_at    timestamptz  not null default now(),
  updated_at    timestamptz  not null default now()
);

create unique index if not exists users_email_lower_key on users (lower(email));

drop trigger if exists users_set_updated_at on users;
create trigger users_set_updated_at
  before update on users
  for each row execute function set_updated_at();

-- -----------------------------------------------------------------------------
-- warehouses: a floor plan. Dimensions are expressed in meters.
-- layout_version implements optimistic concurrency for layout saves.
-- -----------------------------------------------------------------------------
create table if not exists warehouses (
  id             uuid primary key default gen_random_uuid(),
  owner_id       uuid          not null references users (id) on delete cascade,
  name           varchar(80)   not null,
  description    varchar(500),
  width          double precision not null check (width  >= 5 and width  <= 2000),
  height         double precision not null check (height >= 5 and height <= 2000),
  layout_version integer       not null default 0,
  created_at     timestamptz   not null default now(),
  updated_at     timestamptz   not null default now()
);

create index if not exists warehouses_owner_updated_idx on warehouses (owner_id, updated_at desc);

drop trigger if exists warehouses_set_updated_at on warehouses;
create trigger warehouses_set_updated_at
  before update on warehouses
  for each row execute function set_updated_at();

-- -----------------------------------------------------------------------------
-- warehouse_elements: every shape placed on the floor plan.
--   x / y      top-left corner of the element (meters), before rotation
--   rotation   degrees clockwise around (x, y), normalised to [0, 360)
--   properties type-specific settings, validated by the API:
--     zone     { "category": "reception" | "picking" | ... }
--     rack     { "code": "A", "rows": 3, "columns": 6 }
--     dock     { "direction": "inbound" | "outbound" | "mixed" }
--     door     { "kind": "personnel" | "sectional" | "emergency" }
--     obstacle { "kind": "column" | "wall" | "machine" | "other" }
--   sort_order drawing order inside the editor (lower values are drawn first)
--   deleted_at soft delete, only used for racks that still hold stock so an
--              undo in the editor can restore them with their contents.
--
-- ids are generated by the editor (UUID v4) so undo/redo can recreate an
-- element with the same identity.
-- -----------------------------------------------------------------------------
create table if not exists warehouse_elements (
  id           uuid primary key,
  warehouse_id uuid             not null references warehouses (id) on delete cascade,
  type         varchar(16)      not null check (type in ('zone', 'rack', 'dock', 'door', 'obstacle')),
  name         varchar(80)      not null,
  x            double precision not null,
  y            double precision not null,
  width        double precision not null check (width  > 0),
  height       double precision not null check (height > 0),
  rotation     double precision not null default 0 check (rotation >= 0 and rotation < 360),
  color        varchar(7)       check (color ~ '^#[0-9a-fA-F]{6}$'),
  properties   jsonb            not null default '{}'::jsonb,
  sort_order   integer          not null default 0,
  deleted_at   timestamptz,
  created_at   timestamptz      not null default now(),
  updated_at   timestamptz      not null default now(),
  constraint warehouse_elements_rack_properties_chk check (
    type <> 'rack'
    or (properties ? 'code' and properties ? 'rows' and properties ? 'columns')
  )
);

create index if not exists warehouse_elements_warehouse_idx
  on warehouse_elements (warehouse_id)
  where deleted_at is null;

drop trigger if exists warehouse_elements_set_updated_at on warehouse_elements;
create trigger warehouse_elements_set_updated_at
  before update on warehouse_elements
  for each row execute function set_updated_at();

-- -----------------------------------------------------------------------------
-- rack_locations: one row per storage position of a rack (row = level,
-- column = bay). Code format: <RACK CODE>-<ROW 2 digits>-<COLUMN 2 digits>,
-- e.g. A-01-03. Locations are created by the API when a rack is saved.
-- -----------------------------------------------------------------------------
create table if not exists rack_locations (
  id            uuid primary key default gen_random_uuid(),
  element_id    uuid        not null references warehouse_elements (id) on delete cascade,
  row_number    smallint    not null check (row_number    between 1 and 99),
  column_number smallint    not null check (column_number between 1 and 99),
  code          varchar(24) not null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint rack_locations_position_key unique (element_id, row_number, column_number)
);

create index if not exists rack_locations_code_idx on rack_locations (code);

drop trigger if exists rack_locations_set_updated_at on rack_locations;
create trigger rack_locations_set_updated_at
  before update on rack_locations
  for each row execute function set_updated_at();

-- -----------------------------------------------------------------------------
-- location_contents: what is stored in a location (at most one article).
-- A location without a row here is empty.
-- -----------------------------------------------------------------------------
create table if not exists location_contents (
  id           uuid primary key default gen_random_uuid(),
  location_id  uuid         not null references rack_locations (id) on delete cascade,
  article_code varchar(40)  not null,
  description  varchar(160),
  quantity     integer      not null check (quantity > 0),
  lot          varchar(40),
  created_at   timestamptz  not null default now(),
  updated_at   timestamptz  not null default now(),
  constraint location_contents_location_key unique (location_id)
);

create index if not exists location_contents_article_trgm_idx
  on location_contents using gin (article_code gin_trgm_ops);

create index if not exists location_contents_description_trgm_idx
  on location_contents using gin (description gin_trgm_ops);

drop trigger if exists location_contents_set_updated_at on location_contents;
create trigger location_contents_set_updated_at
  before update on location_contents
  for each row execute function set_updated_at();
